### ISSUE TITLE
Appears to be broken by npm@7 (workspaces?)

### ISSUE THREAD

**Issue by dantman** [CollinearGroup/license-validator#24]
I upgraded to npm@7 to use npm workspaces in a new project. `license-validator` appears to have been broken by the update.

This appears to be because npm has added a second JSON doc to the output.

i.e. After the expected information there is a second JSON object for the error where npm lists "missing" package warnings (which aren't actually missing).
```json
{
  "version": "...",
  "name": "...",
  ...

}
{
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "...",
    "detail": ""
  }
}
```

**Comment by dantman** [comment]
Hmmm... strange. In the root workspace license-validator runs fine. Even though `npm list --json` still contains an error for extraneous packages.

**Comment by dantman** [comment]
The error when running in a workspace folder is:
```
undefined:241
{
^

SyntaxError: Unexpected token { in JSON at position 7349
    at parse (<anonymous>)
    at ChildProcess.<anonymous> (../node_modules/license-validator/built/checker.js:232:33)
    at ChildProcess.emit (events.js:326:22)
    at maybeClose (internal/child_process.js:1047:16)
    at Socket.<anonymous> (internal/child_process.js:438:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:672:12)
```

**Comment by kingnebby** [comment]
Thanks for the feedback, I'll try to look into this.

**Comment by johnsteenson** [comment]
I am investigating this.  Does NPM7 consistently list two blocks when you run "npm list --json", or is it only in certain types of projects?  I'm trying to replicate locally, and so far, I only see a single block.

**Comment by dantman** [comment]
The second block is an error block. So try intentionally introducing a peer dependency warning.

Also try setting up npm workspaces. This may be a workspace specific issue. I'm actually not sure how npm intends this to work.

**Comment by johnsteenson** [comment]
I was able to replicate it.  It looks like "npm list --json" prints error information because of errors due to extraneous dependencies (I get it when I run in the root, but not in the individual projects).  I took a look through their error board and I see something similar to what I have happening:  https://github.com/npm/cli/issues/1942
